//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("DevAudit.CommandLine")]
[assembly: System.Reflection.AssemblyDescription("DevAudit command-line interface.")]
[assembly: System.Reflection.AssemblyCompany("Vör Security")]
[assembly: System.Reflection.AssemblyProduct("DevAudit")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Vör Security 2016")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("86ee75fc-d05d-42bc-b2c2-b80cf3734332")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")]


